global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'streamlit_apps'
    metrics_path: /metrics
    static_configs:
      - targets: ['app1:8000','app2:8000','app3:8000']

  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx:9113']   # optional if you run nginx exporter
